import { getSession } from 'next-auth/client';
import Head from 'next/head';

import { Header } from '../components/Header';
import { Login } from '../components/Login';

export default function Home(props: any) {
  console.log('session---', props);
  if (!props.session) {
    return <Login />;
  }
  return (
    <div>
      <Head>
        <title>FaceBook Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      {/* Main
        Side bar
        Feed
        Widgets
      Body */}
      {/* Footer body */}
    </div>
  );
}

// we need to make this page server side renedered.
// by adding one function we make this page to be
// server side rendered.

export const getServerSideProps = async (context: any) => {
  // Get a User
  const session = await getSession(context);

  return {
    props: {
      session,
    },
  };
};
